//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeorgiaStockings.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Stocking
    {
        public int StockingId { get; set; }

        [StringLength(50)]
        public string WaterBody { get; set; }

        [StringLength(50)]
        public string County { get; set; }

        public Nullable<int> ScheduleId { get; set; }

        public Nullable<int> NoteId { get; set; }
    
        public virtual Note Note { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
