//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeorgiaStockings.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GeorgiaStockingsEntities : DbContext
    {
        public GeorgiaStockingsEntities()
            : base("name=GeorgiaStockingsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<Stocking> Stockings { get; set; }
    
        [DbFunction("GeorgiaStockingsEntities", "Split")]
        public virtual IQueryable<Split_Result> Split(string delimiter, string @string)
        {
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            var stringParameter = @string != null ?
                new ObjectParameter("String", @string) :
                new ObjectParameter("String", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Split_Result>("[GeorgiaStockingsEntities].[Split](@Delimiter, @String)", delimiterParameter, stringParameter);
        }
    
        public virtual ObjectResult<GetScheduleByCounty_Result> GetScheduleByCounty(string countyID)
        {
            var countyIDParameter = countyID != null ?
                new ObjectParameter("CountyID", countyID) :
                new ObjectParameter("CountyID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetScheduleByCounty_Result>("GetScheduleByCounty", countyIDParameter);
        }
    }
}
